allow networks to be created from Boolean logic text file
rionbr/CANA pull request #4
Opened 2018-05-02 18:37 UTC by tjparmer

Included changes to allow the network to be read in from a Boolean logic text file (as used by Reka Albert's lab), exemplar leukemia and breast cancer text files, and updates to the breast cancer tutorial to reformat the effective graph to mimic Figure 3 from the respective paper

2018-05-03 17:49 UTC, rionbr requested changes

2018-05-03 17:49 UTC, rionbr commented on cana/utils.py
> +	'''
Thomas, can we have an example in the docstring of what this functions does?

2018-05-03 17:49 UTC, rionbr commented on cana/datasets/leukemia.txt
> +#BOOLEAN RULES
We need to add a line of comment before the file start with the reference from the paper. I believe some of the other files also have that. Take a look at them.

2018-05-03 17:49 UTC, rionbr commented on cana/boolean_network.py
> +	def from_text(cls, input_file, keep_constants=True, **kwargs):
So now we have two function "from_text" and "from_string" .. It is not intuitive that they do different things. I believe "from_text" deals with Albert format, "from_string" deals with cnet format.

Perhaps we should have one function called "from_string" with a parameter that then calls other functions depending on the format. Let's talks about this more.

2018-06-05 16:14 UTC, tjparmer commented
I've addressed the three points you mentioned above.  I have also created a keyword argument for from_file so that it can accept either cnet format or Albert's boolean rules format.  The default is cnet which calls from_string, so that the older code doesn't break.  I tested with the old networks (Thaliana, drosophila) and the new cancer networks to make sure they still work.

2018-11-28 19:56 UTC, rionbr approved these changes

2018-11-28 20:00 UTC, merged

2018-11-28 20:02 UTC, rionbr commented
Self note: I wanted to change some things on @tjparmer pull request before merging. I wasn't able to do that, so now I've merged and will update some variables.