BooleanNode.from_partial_lut with bias and effective connectivity criteria
rionbr/CANA pull request #46
Opened 2024-06-17 22:32 UTC by srikanth-iyer

created a function under BooleanNode to generate a node from partial LUT. a
added fill missing values randomly option
added required bias option
added required effective connectivity option

also, did some code clean up on some old code using ruff linter.

NOTE: Need to add some tests. Will do this in next iteration.

2024-06-18 19:11 UTC, jcrozum requested changes

2024-06-18 19:11 UTC, jcrozum commented on cana/boolean_network.py
>      def from_string_cnet(self, string, keep_constants=True, **kwargs):
add option to retain old behavior in which prime implicant input is assumed

2024-06-18 19:11 UTC, jcrozum commented on cana/boolean_node.py
> -        """Instanciate a Boolean Node from a output transition list.
let's revert this for now. We don't have a way to know which inputs are missing yet

2024-06-18 19:11 UTC, jcrozum commented on cana/boolean_node.py
> +            print("Error (schemata_look_up_table): The outputs contain missing values. Please fill the missing values before generating the schemata look-up table.")
raise exception instead or warning

2024-06-18 19:11 UTC, jcrozum commented on cana/datasets/bio.py
> +def PARTIAL_LUTS_DEMO():
move somewhere else (not bio)

2024-06-18 19:11 UTC, jcrozum commented on cana/drawing/schema_vis.py
> +        print("Error (plot_schemata()): The output contains '?'")
raise error

2024-06-18 19:11 UTC, jcrozum commented on cana/boolean_node.py
> +            if '?' in generated_node.outputs:
```python
if verbose and '?' in generated_node.outputs:
    print('...')
```

2024-06-18 19:11 UTC, jcrozum commented on cana/boolean_node.py
> +    def bias(self, verbose=True):
usually verbose options are false by default

2024-06-18 19:11 UTC, jcrozum commented on cana/boolean_node.py
> +    def from_partial_lut(partial_lut, fill_missing_output_randomly = False, required_node_bias = None, required_effective_connectivity= None,verbose= True, *args, **kwargs):
looks like maybe this didn't go through the linter?

2024-06-18 19:11 UTC, jcrozum commented on cana/utils.py
> +def fill_out_lut(partial_lut, verbose= False):
spacing makes me think this didn't get linted either

2024-06-18 19:11 UTC, jcrozum commented on cana/utils.py
> +            raise ValueError('All the input entries of the partial LUT must be valid binary strings.')
this error message is misleading--we can have strings like `'012x--x#'` and so on, which are not binary

2024-06-18 19:11 UTC, jcrozum commented on cana/utils.py
> +        elif any([x in ['-', '#','2','x'] for x in entry[0]]):
I see this list in several places; maybe we should define it as a variable, e.g., as the sets
```python
unknown_output_symbols = {'-','#','2','x'}
unknown_input_symbols = {'-','#','2','x','!','?'}
```
(or something like that)

2024-06-18 19:11 UTC, jcrozum commented on cana/utils.py
> +        elif any([x in ['-', '#','2','x'] for x in entry[0]]):
Also, I'm a bit confused about whether/when `'?'` and `'!'` are allowed

2024-06-18 19:11 UTC, jcrozum commented on cana/utils.py
> +    all_states = {entry[0]: entry[1] for entry in partial_lut}
just fyi, this works:
```python
all_states = dict(partial_lut)
```

2024-06-18 19:11 UTC, jcrozum commented on cana/boolean_node.py
> +            min_achievable_bias = generated_node.bias(verbose=False)
this relies on the bias function treating unknowns like zeros, which is weird. We might want to change that in the future, so it's probably a good idea to just calculate `min_achievable_bias` directly, as you've done for its max counterpart

2024-06-18 19:11 UTC, jcrozum commented on cana/boolean_node.py
> +            min_achievable_bias = generated_node.bias(verbose=False)
you already have `current_ones` below, so this would just be 
```python
min_achievable_bias = current_ones / 2**generated_node.k
```
right?

2024-06-18 19:11 UTC, jcrozum commented on cana/boolean_node.py
> +    def from_partial_lut(partial_lut, fill_missing_output_randomly = False, required_node_bias = None, required_effective_connectivity= None,verbose= True, *args, **kwargs):
need more tests to make sure it works

2024-06-18 19:11 UTC, jcrozum commented on cana/boolean_node.py
> +        Returns:
make this return a list of all the ones that are "best"

2024-06-18 19:11 UTC, jcrozum commented on cana/boolean_node.py
> +                generated_node_permutations[count] = BooleanNode.from_output_list(generated_outputs)
refactor `generated_node_permutations` into its own function. It will be useful all on its own (probably)

2024-06-19 21:52 UTC, srikanth-iyer commented on cana/boolean_node.py
> +    def from_partial_lut(partial_lut, fill_missing_output_randomly = False, required_node_bias = None, required_effective_connectivity= None,verbose= True, *args, **kwargs):
i have removed the generate extra lines in the table section. However, I have kept the section that replaces 'None', '-', '#', or 'x' with '-'. I need this because i use this for other functions. This shouldn't affect other existing functions since the output list will be complete for all of them anyway.

originally, the code doesn't check if the length of output.  i've added a raise ValueError if the length of output list isn't 2**k

2024-06-27 17:44 UTC, closed without merging